name: CI 

on:
# Can also trigger on a push, would run tests on any push
  push: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: CI
    uses: msingleton0928/reusable-workflows/.github/workflows/reusable-build.yml@main
    with:
      dotnet_version: 9.0.x