name: PR Verify

on:
# Can also trigger on a push, would run tests on any push
  pull_request: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: PR Verify
    uses: msingleton0928/reusable-workflows/.github/workflows/reusable-build.yml@main
    with:
      dotnet_version: 9.0.x


